---
title: "bt maize regressions"
author: "Courtney Cooper"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import Panel Data

```{r data, include=FALSE}
rm(list=ls()) # Caution: this clears the Environment

if (!require("pacman")) install.packages("pacman")
install.packages('gtsummary')
library(pacman)
library(sandwich,
       lmtest,
       gtsummary)
install.packages("ggsci")
install.packages('modelsummary')
install.packages("equatiomatic")
library(equatiomatic)
library(ggsci)
install.packages("maptools", repos="http://R-Forge.R-project.org")
library(maptools)
library(modelsummary)
library(kableExtra)
library(gt)




dat <- readRDS("data/finalpanel.rds")

```

### Generate Alternate Models

```{r data, include=FALSE}
#cult has more than 10 obs per year
altpanel1 <- dat
summarycult <- altpanel1 %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult <- summarycult[summarycult$count < 10,]

altpanel1 <- merge(altpanel1,summarycult, by = c("year","cultivar_name"),all = TRUE, no.dups= TRUE)
names(altpanel1)[names(altpanel1) == 'count'] <- 'cult_nvals'
altpanel1$cult_nvals <- if_else(altpanel1$cult_nvals %in% c(NA), "0", "1")
altpanel1 <- altpanel1[!altpanel1$cult_nvals== "1", ]

altpanel1 <- altpanel1[,c("year", "cultivar_name", "provence", "locality", 
              "rep", "yield", "color", "technology", "crop",
              "irrigated", "release_year", "bt")]

#cult in more than 3 years
altpanel2 <- dat
summarycult <- altpanel2 %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult2 <- summarycult %>% group_by(cultivar_name) %>% summarise(count = n())
summarycult2 <- summarycult2[summarycult2$count < 3,]

altpanel2 <- merge(altpanel2,summarycult2, by = c("cultivar_name"),all = TRUE, no.dups= TRUE)
names(altpanel2)[names(altpanel2) == 'count'] <- 'cult_nvals'
altpanel2$cult_nvals <- if_else(altpanel2$cult_nvals %in% c(NA), "0", "1")
altpanel2 <- altpanel2[!altpanel2$cult_nvals== "1", ]

altpanel2 <- altpanel2[,c("year", "cultivar_name", "provence", "locality", 
              "rep", "yield", "color", "technology", "crop",
              "irrigated", "release_year", "bt")]

#cult in more than 5 years
altpanel3 <- dat
summarycult <- altpanel3 %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult2 <- summarycult %>% group_by(cultivar_name) %>% summarise(count = n())
summarycult2 <- summarycult2[summarycult2$count < 5,]

altpanel3 <- merge(altpanel3,summarycult2, by = c("cultivar_name"),all = TRUE, no.dups= TRUE)
names(altpanel3)[names(altpanel3) == 'count'] <- 'cult_nvals'
altpanel3$cult_nvals <- if_else(altpanel3$cult_nvals %in% c(NA), "0", "1")
altpanel3 <- altpanel3[!altpanel3$cult_nvals== "1", ]

altpanel3 <- altpanel3[,c("year", "cultivar_name", "provence", "locality", 
              "rep", "yield", "color", "technology", "crop",
              "irrigated", "release_year", "bt")]

#cult has 10 obs per year in more than 3 years
altpanel4 <- altpanel1
summarycult <- altpanel4 %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult2 <- summarycult %>% group_by(cultivar_name) %>% summarise(count = n())
summarycult2 <- summarycult2[summarycult2$count < 3,]

altpanel4 <- merge(altpanel4,summarycult2, by = c("cultivar_name"),all = TRUE, no.dups= TRUE)
names(altpanel4)[names(altpanel4) == 'count'] <- 'cult_nvals'
altpanel4$cult_nvals <- if_else(altpanel4$cult_nvals %in% c(NA), "0", "1")
altpanel4 <- altpanel4[!altpanel4$cult_nvals== "1", ]

altpanel4 <- altpanel4[,c("year", "cultivar_name", "provence", "locality", 
              "rep", "yield", "color", "technology", "crop",
              "irrigated", "release_year", "bt")]


#locality in at least than 5 years
altpanel5 <- dat
summaryloc <- altpanel5 %>% group_by(year, locality) %>% 
  summarise(count = n()) # check location if in more than one year
summaryloc <- summaryloc %>% group_by(locality) %>% 
  summarise (count = n())
summaryloc <- summaryloc[summaryloc$count < 5,]
altpanel5 <- merge(altpanel5,summaryloc, by = c("locality"),all = TRUE, no.dups= TRUE)
names(altpanel5)[names(altpanel5) == 'count'] <- 'loc_nvals'
altpanel5$loc_nvals <- if_else(altpanel5$loc_nvals %in% c(NA), "0", "1")
altpanel5 <- altpanel5[!altpanel5$loc_nvals== "1", ]

altpanel5 <- altpanel5[,c("year", "cultivar_name", "provence", "locality", 
              "rep", "yield", "color", "technology", "crop",
              "irrigated", "release_year", "bt")]

rm(summarycult, summarycult2, summaryloc)
```

### Regressions

```{r data, include=FALSE}
dat %>%
  group_by(year) %>%
  summarise(mean = mean(yield, na.rm=T))



## require 5 obs per year per province
summaryobs <- dat %>% group_by(year, provence, color, bt) %>%
  summarise(count = n()) # check bt if in more than one observation per province/year
summaryobs <- summaryobs[summaryobs$count < 5,]
summaryobs$count <- "1"
dat <- merge(dat,summaryobs, by = c("year","provence", "bt","color"),all = TRUE, no.dups= TRUE)
dat$count <- if_else(dat$count %in% c(NA), "0", "1")
dat <- dat[!dat$count== "1", ]

summaryobs <- dat %>% group_by(technology, year, provence, color) %>%
  summarise(count = n())


dat$GM <- 0
dat$GM <- ifelse(dat$technology != "conv", 1, 0)

bandconv <- dat[dat$technology %in% c("B", "conv"),]
bandconv <- bandconv[!bandconv$provence == "LP",]

dat <- bandconv


summarynew <- dat %>% group_by(provence,color, technology, year, .add = FALSE) %>% 
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

summaryyellow <- dat[!dat$color == "yellow",] %>% group_by(provence, technology, year, .add = FALSE) %>% 
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

reg1 <- glm(yield ~ GM + color + provence + factor(year) + irrigated,data = dat)
summary(reg1)

dat$yearsq <- dat$year*dat$year

reg2 <- glm(yield ~ GM + color + year*GM + yearsq*GM + provence + factor(year)+ irrigated,data = dat)
summary(reg2)


dat$y_effect <- reg2$coefficients["GM"] + reg2$coefficients["GM:year"] * dat$year
dat$ysq_effect <- reg2$coefficients["GM"] + reg2$coefficients["GM:year"] * dat$year + reg2$coefficients["GM:yearsq"] * dat$yearsq

max(dat$ysq_effect)


# Provence by year by GM effects in one model

reg3 <- glm(yield ~ GM + color+ year*provence*GM + provence*yearsq*GM + provence + factor(year)+ + irrigated,data = dat)
summary(reg3)

models <- list(reg1,reg2,reg3)

extract_eq(reg1)
extract_eq(reg2)
extract_eq(reg3)




modelregress <- msummary(models, vcov = vcovHC, stars = TRUE)
print(modelregress)
#reduced <- c('(Intercept)' = 'Constant',
             'provenceFS' = "Free State",
             'provenceGP' = "GP",
             'provenceKZN' = "KZN",
             'provenceMP' = "MP",
             'provenceNC' = "NC",
             'provenceNW' = "NW",
             'provenceWS' = "WS",
             'GM' = "GM",
             'coloryellow' = "Color (yellow)",
             'irrigated' = "Irrigated",
             'GM x year' = "GM x year",
             'GM x yearsq' = "GM x yearsq"
             )

msummary(modelregress, coef_map = reduced)


install.packages("stargazer")
library(stargazer)
stargazer(reg1, reg2, reg3, title="Regression Results",out = "output/regress.html", align=TRUE, omit = c(":",  "factor\\(year\\)1982","factor\\(year\\)1984","factor\\(year\\)1985","factor\\(year\\)1986","factor\\(year\\)1987","factor\\(year\\)1988","factor\\(year\\)1989","factor\\(year\\)1990","factor\\(year\\)1991","factor\\(year\\)1993","factor\\(year\\)1994","factor\\(year\\)1995","factor\\(year\\)1996","factor\\(year\\)1997","factor\\(year\\)1998","factor\\(year\\)1999","factor\\(year\\)2000","factor\\(year\\)2001","factor\\(year\\)2002","factor\\(year\\)2003","factor\\(year\\)2004","factor\\(year\\)2005","factor\\(year\\)2006","factor\\(year\\)2007","factor\\(year\\)2008","factor\\(year\\)2009","factor\\(year\\)2010","factor\\(year\\)2011","factor\\(year\\)2012","factor\\(year\\)2013","factor\\(year\\)2014","factor\\(year\\)2015","factor\\(year\\)2016","factor\\(year\\)2017","factor\\(year\\)2018","factor\\(year\\)2019"))


#1
FS <- dat[dat$provence == "FS",]
FS <- FS[!FS$year == "2004",]
fs_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=FS)
summary(fs_reg)

FS$y_effect <- fs_reg$coefficients["GM"] + fs_reg$coefficients["GM:year"] * FS$year
FS$ysq_effect <- fs_reg$coefficients["GM"] + fs_reg$coefficients["GM:year"] * FS$year + fs_reg$coefficients["GM:yearsq"] * FS$yearsq


#2
GP <- dat[dat$provence == "GP",]
gp_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=GP)
summary(gp_reg)

GP$y_effect <- gp_reg$coefficients["GM"] + gp_reg$coefficients["GM:year"] * GP$year
GP$ysq_effect <- gp_reg$coefficients["GM"] + gp_reg$coefficients["GM:year"] * GP$year + gp_reg$coefficients["GM:yearsq"] * GP$yearsq

#3
MP <- dat[dat$provence == "MP",]
mp_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=MP)
summary(mp_reg)

MP$y_effect <- mp_reg$coefficients["GM"] + mp_reg$coefficients["GM:year"] * MP$year
MP$ysq_effect <- mp_reg$coefficients["GM"] + mp_reg$coefficients["GM:year"] * MP$year + mp_reg$coefficients["GM:yearsq"] * MP$yearsq

#4
NW <- dat[dat$provence == "NW",]
nw_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=NW)
summary(nw_reg)

NW$y_effect <- nw_reg$coefficients["GM"] + nw_reg$coefficients["GM:year"] * NW$year
NW$ysq_effect <- nw_reg$coefficients["GM"] + nw_reg$coefficients["GM:year"] * NW$year + nw_reg$coefficients["GM:yearsq"] * NW$yearsq

#5
KZN <- dat[dat$provence == "KZN",]
kzn_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=KZN)
summary(kzn_reg)

KZN$y_effect <- kzn_reg$coefficients["GM"] + kzn_reg$coefficients["GM:year"] * KZN$year
KZN$ysq_effect <- kzn_reg$coefficients["GM"] + kzn_reg$coefficients["GM:year"] * KZN$year + kzn_reg$coefficients["GM:yearsq"] * KZN$yearsq

#6
EC <- dat[dat$provence == "EC",]
ec_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=EC)
summary(ec_reg)

EC$y_effect <- ec_reg$coefficients["GM"] + ec_reg$coefficients["GM:year"] * EC$year
EC$ysq_effect <- ec_reg$coefficients["GM"] + ec_reg$coefficients["GM:year"] * EC$year + ec_reg$coefficients["GM:yearsq"] * EC$yearsq

#7 ##REMOVED LP FROM DATA#
#LP <- dat[dat$provence == "LP",]
#lp_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=LP)
#summary(lp_reg)

#LP$y_effect <- lp_reg$coefficients["GM"] + lp_reg$coefficients["GM:year"] * LP$year
#LP$ysq_effect <- lp_reg$coefficients["GM"] + lp_reg$coefficients["GM:year"] * LP$year + lp_reg$coefficients["GM:yearsq"] * LP$yearsq

#8
NC <- dat[dat$provence == "NC",]
nc_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=NC)
summary(nc_reg)

NC$y_effect <- nc_reg$coefficients["GM"] + nc_reg$coefficients["GM:year"] * NC$year
NC$ysq_effect <- nc_reg$coefficients["GM"] + nc_reg$coefficients["GM:year"] * NC$year + nc_reg$coefficients["GM:yearsq"] * NC$yearsq
      
#9
WC <- dat[dat$provence == "WC",]
wc_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=WC)
summary(wc_reg)

WC$y_effect <- wc_reg$coefficients["GM"] + wc_reg$coefficients["GM:year"] * WC$year
WC$ysq_effect <- wc_reg$coefficients["GM"] + wc_reg$coefficients["GM:year"] * WC$year + wc_reg$coefficients["GM:yearsq"] * WC$yearsq

#combine NC, NW, FS
northregion <- bind_rows(NC, NW, FS)
north_reg <- glm(yield ~ factor(year)+ GM + year*GM + yearsq*GM + color + irrigated, data=northregion)
summary(north_reg)

northregion$y_effect <- north_reg$coefficients["GM"] + north_reg$coefficients["GM:year"] * northregion$year
northregion$ysq_effect <- north_reg$coefficients["GM"] + north_reg$coefficients["GM:year"] * northregion$year + north_reg$coefficients["GM:yearsq"] * northregion$yearsq

northregion$provence <- "northregion"
prov <- rbind(northregion, GP, MP, KZN, WC)


summarywc <- WC %>% group_by(year, GM, color, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T),
            ysqeffect = mean(ysq_effect, na.rm = T))


```

###Alt Model Regressions

```{r data, include=FALSE}

##Alt Model 1
alt1reg1 <- glm(yield ~ provence + factor(year) + bt + color + irrigated, data=altpanel1)
summary(alt1reg1)
altpanel1$yearsq <- altpanel1$year*altpanel1$year

alt1reg2 <- glm(yield ~ provence + factor(year)+ bt + year*bt + yearsq*bt + color + irrigated, data=altpanel1)
summary(alt1reg2)


##Alt Model 2
alt2reg1 <- glm(yield ~ provence + factor(year) + bt + color + irrigated, data=altpanel2)
summary(alt2reg1)
altpanel2$yearsq <- altpanel2$year*altpanel2$year

alt2reg2 <- glm(yield ~ provence + factor(year)+ bt + year*bt + yearsq*bt + color + irrigated, data=altpanel2)
summary(alt2reg2)


##Alt Model 3
alt3reg1 <- glm(yield ~ provence + factor(year) + bt + color + irrigated, data=altpanel3)
summary(alt3reg1)
altpanel3$yearsq <- altpanel3$year*altpanel3$year

alt3reg2 <- glm(yield ~ provence + factor(year)+ bt + year*bt + yearsq*bt + color + irrigated, data=altpanel3)
summary(alt3reg2)


##Alt Model 4
alt4reg1 <- glm(yield ~ provence + factor(year) + bt + color + irrigated, data=altpanel4)
summary(alt4reg1)
altpanel4$yearsq <- altpanel4$year*altpanel4$year

alt4reg2 <- glm(yield ~ provence + factor(year)+ bt + year*bt + yearsq*bt + color + irrigated, data=altpanel4)
summary(alt4reg2)


##Alt Model 5
alt5reg1 <- glm(yield ~ provence + factor(year) + bt + color + irrigated, data=altpanel5)
summary(alt5reg1)
altpanel5$yearsq <- altpanel5$year*altpanel5$year

alt5reg2 <- glm(yield ~ provence + factor(year)+ bt + year*bt + yearsq*bt + color + irrigated, data=altpanel5)
summary(alt5reg2)



altmodels <- list(alt1reg1,alt2reg1,alt3reg1,alt4reg1,alt5reg1)

install.packages("magick")
install.packages("webshot")
reduced2 <- c('(Intercept)' = 'Constant',
             'provenceFS' = "Free State",
             'provenceGP' = "GP",
             'provenceKZN' = "KZN",
             'provenceMP' = "MP",
             'provenceNC' = "NC",
             'provenceNW' = "NW",
             'provenceWS' = "WS",
             'bt' = "Bt",
             'coloryellow' = "Color (yellow)",
             'irrigated' = "Irrigated",
             'bt x year' = "Bt x year",
             'bt x yearsq' = "Bt x yearsq"
             )
altmodelregress <- msummary(altmodels,coef_map = reduced2, vcov = vcovHC, stars = TRUE)
print(altmodelregress)

msummary(models, coef_map = reduced)



```

### yield gains peak

```{r data, include=FALSE}
breakpoint <- data.frame(0,0,0)
colnames(breakpoint) <- c('provence', 'ysq_effectmax')
provence <- c("northregion", 'GP', 'MP', 'KZN', 'WC')

ysq_effect <- c(max(northregion$ysq_effect), 
                max(GP$ysq_effect), 
                max(MP$ysq_effect), 
                max(KZN$ysq_effect), 
                max(WC$ysq_effect))


breakpoint <- data.frame(provence, ysq_effect)
rm(provence, ysq_effect)
prov2 <- prov[,c("provence", "ysq_effect", "year")]
breakpoint <- merge(breakpoint, prov2, by = c("ysq_effect","provence"), no.dups = TRUE)
prov3 <- prov2[!duplicated(prov2), ]

breakpoint <- breakpoint[!duplicated(breakpoint), ]

summaryb <- prov %>% filter(bt == 1) %>% group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

breakpoint <- merge(breakpoint, summaryb, by = c("provence","year"), no.dups = TRUE)

summaryb2 <- prov %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(count = n())

breakpoint2 <- merge(breakpoint, summaryb2, by = c("provence","year","color"), no.dups = TRUE)
breakpoint2 <- breakpoint2[,c("year", "provence", "color", "ysq_effect", "mean", "SD", "count")]
breakpoint2 <- breakpoint2[!duplicated(breakpoint2), ]

write.csv(breakpoint2, "output/breakpoint.csv")

ggbreak <- ggplot(prov3,aes(year,ysq_effect))+
  geom_smooth(aes(color=provence), size = 1) +
  theme_bw() + coord_cartesian(xlim= c(1999,2020), ylim = c(-.05,.6), clip = "on")
ggbreak

proveffects <- breakpoint2 %>%
  gt(rowname_col = "province") %>%
  tab_header(
    title = "Province Effects",
    subtitle = glue::glue("observations included in sample")
  ) %>%
  cols_label(
    year = html("Year"),
    provence = html("Province"),
    ysq_effect = html("Yield Gain Peak"),
    mean = html("Average Yield"),
    SD = html("Yield SD"),
    count = html("num of observations")) %>%
  cols_align(
    align = "center",
    columns = everything())  %>%
  fmt_number(
    columns = 4:6,
    decimals = 3)

print(proveffects)

summtbl <- prov %>% filter(technology == "B") %>% 
  group_by(provence, technology, year,  .add = FALSE) %>% 
  summarise(yield = mean(yield, na.rm = T),
            SD = sd(yield, na.rm = T))
summtbl2 <- prov %>% filter(technology == "B") %>%
  group_by(year, provence, technology) %>%
  count()

write.csv(summtbl2, "output/btobs.csv")

##finding lost gains BY PROV
maizeprod <- read.csv("data/metadata/maizeproduction.csv")

names(maizeprod)[2:7] <- c("percentBt","percentwhite", "percentyellow", "whiteprice", "yellowprice", "totalmaizeht")
maizeprod$percentBt <- ifelse(is.na(maizeprod$percentBt), .29, maizeprod$percentBt)
maizeprod$Bthectare <- maizeprod$percentBt*maizeprod$totalmaizeht
maizeprod$totalprice <- maizeprod$percentwhite*maizeprod$whiteprice + maizeprod$percentyellow*maizeprod$yellowprice


# GP Loss
gploss <- GP %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
gploss <- merge(GP, gploss, by = c("provence","year","color"), no.dups = TRUE)
gploss <- gploss[,c("year", "provence", "color","technology", "ysq_effect", "mean", "SD")]

gploss <- gploss[gploss$technology == "B",]
gploss <- gploss[!duplicated(gploss), ]
gploss$maxysq <- ifelse(gploss$year<2010, NA, max(gploss$ysq_effect))
gploss$gain_loss <- gploss$ysq_effect - gploss$maxysq

gploss <- merge(gploss, maizeprod, by = c("year"), no.dups = TRUE)

gploss$mtloss <- (gploss$gain_loss*gploss$Bthectare)*-1
gploss$yearlyloss <- gploss$mtloss*gploss$totalprice
gploss$dollarlossperht <- gploss$yearlyloss/gploss$Bthectare
gploss <- gploss[,c("year","provence", "color", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss", "dollarlossperht")]

# KZN Loss
kznloss <- KZN %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
kznloss <- merge(KZN, kznloss, by = c("provence","year","color"), no.dups = TRUE)
kznloss <- kznloss[,c("year", "provence", "color","technology", "ysq_effect", "mean", "SD")]

kznloss <- kznloss[kznloss$technology == "B",]
kznloss <- kznloss[!duplicated(kznloss), ]
kznloss$maxysq <- ifelse(kznloss$year<2012, NA, max(kznloss$ysq_effect))
kznloss$gain_loss <- kznloss$ysq_effect - kznloss$maxysq

kznloss <- merge(kznloss, maizeprod, by = c("year"), no.dups = TRUE)

kznloss$mtloss <- (kznloss$gain_loss*kznloss$Bthectare)*-1
kznloss$yearlyloss <- kznloss$mtloss*kznloss$totalprice
kznloss$dollarlossperht <- kznloss$yearlyloss/kznloss$Bthectare
kznloss <- kznloss[,c("year", "provence", "color", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss", "dollarlossperht")]

# MP Loss
mploss <- MP %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
mploss <- merge(MP, mploss, by = c("provence","year","color"), no.dups = TRUE)
mploss <- mploss[,c("year", "provence", "color","technology", "ysq_effect", "mean", "SD")]

mploss <- mploss[mploss$technology == "B",]
mploss <- mploss[!duplicated(mploss), ]
mploss$maxysq <- ifelse(mploss$year<2011, NA, max(mploss$ysq_effect))
mploss$gain_loss <- mploss$ysq_effect - mploss$maxysq

mploss <- merge(mploss, maizeprod, by = c("year"), no.dups = TRUE)

mploss$mtloss <- (mploss$gain_loss*mploss$Bthectare)*-1
mploss$yearlyloss <- mploss$mtloss*mploss$totalprice
mploss$dollarlossperht <- mploss$yearlyloss/mploss$Bthectare
mploss <- mploss[,c("year", "provence", "color", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss", "dollarlossperht")]

# North Region Loss
northloss <- northregion %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
northloss <- merge(northregion, northloss, by = c("provence","year","color"), no.dups = TRUE)
northloss <- northloss[,c("year", "provence", "provence", "color","technology", "ysq_effect", "mean", "SD")]

northloss <- northloss[northloss$technology == "B",]
northloss <- northloss[!duplicated(northloss), ]
northloss$maxysq <- ifelse(northloss$year<2011, NA, max(northloss$ysq_effect))
northloss$gain_loss <- northloss$ysq_effect - northloss$maxysq

northloss <- merge(northloss, maizeprod, by = c("year"), no.dups = TRUE)

northloss$mtloss <- (northloss$gain_loss*northloss$Bthectare)*-1
northloss$yearlyloss <- northloss$mtloss*northloss$totalprice
northloss$dollarlossperht <- northloss$yearlyloss/northloss$Bthectare
northloss <- northloss[,c("year", "provence", "color", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss", "dollarlossperht")]

# WC Loss
wcloss <- WC %>% filter(bt == 1) %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
wcloss <- merge(WC, wcloss, by = c("provence","year","color"), no.dups = TRUE)
wcloss <- wcloss[,c("year", "provence", "color","technology", "ysq_effect", "mean", "SD")]

wcloss <- wcloss[wcloss$technology == "B",]
wcloss <- wcloss[!duplicated(wcloss), ]
wcloss$maxysq <- ifelse(wcloss$year<2010, NA, max(wcloss$ysq_effect))
wcloss$gain_loss <- wcloss$ysq_effect - wcloss$maxysq

wcloss <- merge(wcloss, maizeprod, by = c("year"), no.dups = TRUE)

wcloss$mtloss <- (wcloss$gain_loss*wcloss$Bthectare)*-1
wcloss$yearlyloss <- wcloss$mtloss*wcloss$totalprice
wcloss$dollarlossperht <- wcloss$yearlyloss/wcloss$Bthectare
wcloss <- wcloss[,c("year", "provence", "color", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss", "dollarlossperht")]

## Combining Prov Level Gains Lost
provloss <- rbind(northloss, gploss, mploss, kznloss, wcloss)

##finding lost gains ALL
allb <- dat[dat$technology == "B",]
totalloss <- allb %>% filter(technology == "B") %>%
  group_by(year, .add = FALSE) %>%
  summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
totalloss <- merge(allb, totalloss, by = c("year"), no.dups = TRUE)
totalloss <- totalloss[,c("year", "ysq_effect", "mean", "SD")]
totalloss <- totalloss[!duplicated(totalloss), ]
totalloss$maxysq <- ifelse(totalloss$year<2007, NA, max(totalloss$ysq_effect))
totalloss$gain_loss <- totalloss$ysq_effect - totalloss$maxysq

ggplot(data=totalloss)+
  geom_line(aes(year, ysq_effect)) + 
  geom_line(aes(year, maxysq)) + 
  coord_cartesian(xlim= c(1998,2020), ylim = c(.0,.5), clip = "on")




totalloss <- merge(totalloss, maizeprod, by = c("year"), no.dups = TRUE)

totalloss$mtloss <- (totalloss$gain_loss*totalloss$Bthectare)*-1
totalloss$yearlyloss <- totalloss$mtloss*totalloss$totalprice
totalloss$dollarlossperht <- totalloss$yearlyloss/totalloss$Bthectare
totalloss$kgloss <- totalloss$mtloss*1000
totalloss$rationloss <- totalloss$kgloss/totalloss$consumption
totalloss$totalmaizevalue <- totalloss$totalmt*totalloss$totalprice
totalloss <- totalloss[,c("year", "ysq_effect","maxysq","gain_loss", "mtloss", "yearlyloss","consumption","rationloss", "dollarlossperht","totalmaizevalue")]

# Cleaned Total Loss
write.csv(totalloss, "output/totalloss.csv")

totalloss <- totalloss[totalloss$year > 2006,]


ggloss <- ggplot(totalloss,aes(x = year, y = yearlyloss, fill = year))+
  theme_bw() +
  geom_bar(fill="#3CA9CA", width=.8, stat="identity") +
  scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) +
  labs(title = "Economic Loss") +
  coord_cartesian(xlim= c(2006,2020), clip = "on")
ggloss

ggloss2 <- ggplot(totalloss)+
  theme_bw() +
  geom_bar(aes(x = year, y = totalmaizevalue), fill="#3CA9CA", width=.8, stat="identity") +
  geom_bar(aes(x = year, y = yearlyloss), fill="#95427B", width=.8, stat="identity") +
  scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) +
  labs(title = "Economic Loss") +
  coord_cartesian(xlim= c(2006,2020), clip = "on")
ggloss2


#### summary of of Bt observations in FS


summaryfs <- bonly %>% filter(provence == "FS") %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(count = n())

write.csv(summaryfs, "output/btFSsummary.csv")

#### summary of of Bt observations in EC
summaryec <- bonly %>% filter(provence == "EC") %>%
  group_by(color, year, provence, .add = FALSE) %>%
  summarise(count = n())

### predict economic loss


### map provinces
install.packages("raster")

SA = getData('GADM', country='ZAF', level=1)
NAM = getData('GADM', country='NAM', level=0)
BOT = getData('GADM', country='BWA', level=0)
ZWE = getData('GADM', country='ZWE', level=0)
MOZ = getData('GADM', country='MOZ', level=0)
SWZ = getData('GADM', country='SWZ', level=0)
LSO = getData('GADM', country='LSO', level=0)


SA2 = st_as_sf(SA)
NA2 = st_as_sf(NAM)
BO2 = st_as_sf(BOT)
ZW2 = st_as_sf(ZWE)
MO2 = st_as_sf(MOZ)
SW2 = st_as_sf(SWZ)
LS2 = st_as_sf(LSO)

coordinates_cities <- read.csv("output/locationsummary.csv")
coordinates_cities$count <- coordinates_cities$count/500

summary(coordinates_cities)

coordinates_cities <- arrange(coordinates_cities, desc(count))

ggsa <- ggplot() +
  theme_bw() +
  geom_sf(aes(),SA2, fill = "white") +
  geom_sf(aes(),NA2) +
  geom_sf(aes(),BO2) +
  geom_sf(aes(),ZW2) +
  geom_sf(aes(),MO2) +
  geom_sf(aes(),SW2) +
  geom_sf(aes(),LS2)+
  geom_point(data = coordinates_cities, aes(x = long, y = lat), alpha=0.75, col = "#bbbe64", 
             size= coordinates_cities$count, inherit.aes = FALSE)+
  coord_sf(xlim= c(15,35), ylim= c(-35,-22), clip = "on") +
  labs(title = "Location Coordinates")
  
print(ggsa)
ggsave("ggsa.jpeg", ggsa)



## different specifications - quadratic, sin(year) and cosine(year)
# run for bt and bt stacked only


## peak graphs

prov2 <- prov2[!prov2$provence == "EC",]
prov2 <- prov2[!prov2$provence == "LP",]

prov5 <- prov[!prov$provence == "WC",]
ggplot(data=prov5)+
  geom_line(aes(year, ysq_effect, color=provence), size=1) + 
  scale_color_brewer(palette = "Paired") +
  coord_cartesian(xlim= c(1999,2020), ylim = c(-.05,.55), clip = "on")




###################################
# robustness test

coeftest(reg1, vcov = vcovHC(reg1, type="HC1"))
coeftest(reg2, vcov = vcovHC(reg1, type="HC1"))

######################################

###########################################
# Tables for presentation

reg1t <- summary(reg1, scale = TRUE)


t1 <- tbl_regression(reg1, exponentiate = TRUE)
t2 <- tbl_regression(reg2, exponentiate = TRUE, include = -c(year, yearsq))

mergedt1 <- tbl_merge(tbls = list(t1, t2), tab_spanner = c("**Linear**", "**Quadratic**"))
tbl_summary(mergedt1) %>% as_flex_table()


######################
#graphs for presentation

#box plot for yield by year, bt/non bt
post <- bandconv[bandconv$year > "1999",]

post$bt <- if_else(post$bt == 1, "bt", "conv", missing=NULL)
btgg <- ggplot(post, aes(year, yield, group= interaction(bt, year))) + 
  geom_boxplot(aes(color=bt), size = .75)

btgg2 <- btgg +
  theme_bw() +
  labs(
    x = "Year",
    y = "Yield",
    colour = "Technology Type",
    title = "Yield Differences Between Bt and Conventional Over Time"
  ) +
  scale_colour_manual(values = c("bt" = "#db2763", "conv" = "#628395")) + 
  coord_cartesian(ylim = c(.0,25), clip = "on")
print(btgg2)
ggsave("output/btgg2.jpg",plot=btgg2,device = "jpg")

provboxplot <- ggplot(post, aes(year, yield, group= interaction(bt, year))) + 
  geom_boxplot(aes(color=bt), size = .5, outlier.shape = NA) +
  theme_bw() +
  labs(
    x = "Year",
    y = "Yield",
    colour = "Technology Type",
    title = "Yield Differences Between Bt and Conventional Over Time") +
  scale_colour_manual(values = c("bt" = "#db2763", "conv" = "#628395"))+
  facet_wrap(~provence, scale="free")
print(provboxplot)
ggsave("output/provboxplot.jpg",plot=provboxplot,device = "jpg")


#box plot for yield by year, yellow/white
colgg <- ggplot(post, aes(year, yield, group= interaction(color, year))) + 
  geom_boxplot(aes(color=color), size = .75)
colgg2 <- colgg +
  theme_bw() +
  labs(
    x = "Year",
    y = "Yield",
    colour = "Color",
    title = "Yield Differences Between Yellow and White Over Time"
  ) +
 scale_colour_manual(values = c("yellow" = "#db2763", "white" = "#628395"))+ 
  coord_cartesian(ylim = c(.0,25), clip = "on")
colgg2
ggsave("output/colgg2.jpg",plot=colgg2,device = "jpg")


```
