---
title: "bt maize cleaning"
author: "Courtney Cooper"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Get Data and Preprocess
```{r data, include=FALSE}
rm(list=ls()) # Caution: this clears the Environment

if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(dplyr, ggplot2, stringr, stringi,readr,tidyr)
library(ggplot2)
install.packages("gt")
library(gt)


# Read data and stack

rawdat <- list.files(path="data/rawdat", pattern="*csv", full.names = T)
rawdat <- lapply(rawdat, read.csv)
dat <- do.call("rbind", rawdat)
dat$Region <- tolower(dat$Region)
dat$locality <- tolower(dat$locality)
dat$yield <- as.numeric(dat$yield)

write.csv(dat, "data/allnewyears.csv")
rm(rawdat)

cultivar <- read.csv("data/metadata/cultivarlist.csv")
cultivar$variety_trim <- toupper(cultivar$variety_trim)
cultivar <- cultivar[, !(names(cultivar) %in% c("variety","technology"))]
names(cultivar)[names(cultivar) == "variety_trim"] <- "cultivar_name"
names(cultivar)[names(cultivar) == "X"] <- "technology"
dat$cultivar_name <- toupper(dat$cultivar_name)
dat$cultivar_name <- trimws(dat$cultivar_name, which= c("both"))


# Merge Cultivar Dictionary with New Data

dat <- merge(dat,cultivar,by = "cultivar_name")
names(dat)[names(dat) == "Year"] <- "year"
names(dat)[names(dat) == "Provence"] <- "provence"
names(dat)[names(dat) == "Region"] <- "region"
names(dat)[names(dat) == "Rep"] <- "rep"
names(dat)[names(dat) == "Year"] <- "year"
names(dat)[names(dat) == "breeder.x"] <- "breeder"
dat <- dat[, !(names(dat) %in% c("Yellow","White","variety","breeder.y"))]
dat$alternate <- trimws(dat$alternate, which= c("both"))
rm(cultivar)

dat$color <- tolower(dat$color)
names(dat)[names(dat) == "Irrigated"] <- "irrigated"
dat$technology <- gsub("0", "conv", dat$technology)

dat <- dat[c("year", "region", "provence", "locality", "locality_no", 
             "cultivar_name", "alternate", "cultivar_no", "breeder", 
             "rep", "yield", "color", "technology", "crop", "temp", 
             "irrigated", "number", "release_year")]


write.csv(dat, "data/allnewyearsmerge.csv")
```


### Average and Summaries 

```{r data summaries}

# Initial Table and Graph
summarynew <- dat %>% 
  group_by(color, technology, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(summarynew, aes(year, mean))+ geom_smooth(aes(color=technology), size = 1.25) + theme_bw() + scale_color_jcolors(palette = "pal5")
p

write.csv(summarynew, "output/summary.csv")
```

### Data Merging
```{r data merging, include=false}
olddat <- read.csv("data/metadata/allmaize1980_2010.csv")
location <- read.csv("data/metadata/oldlocality.csv")

location$locality <- tolower(location$locality)
olddat$locality <- tolower(olddat$locality)
olddat <- olddat[!(olddat$yield == "" | is.na(olddat$yield)), ]
olddat <- olddat[olddat$yield >= 0, ]
olddat$cultivar_name <- str_replace_all(string=olddat$cultivar_name, 
                                        pattern=" ", repl="")

olddat$cultivar_n <- str_sub(olddat$cultivar_name,-1) #create columns with last values
olddat$cultivar_n1 <- str_sub(olddat$cultivar_name,-2,-2)
olddat$cultivar_n2 <- str_sub(olddat$cultivar_name,-3,-3)

olddat$color <- ifelse(olddat$cultivar_n %in% c("W",1,3,5,7,9)
                        |olddat$cultivar_n %in% c("B","R") &
                         olddat$cultivar_n1 %in% c(1,3,5,7,9)
                        |olddat$cultivar_n %in% c("B","R") &
                         olddat$cultivar_n1 %in% c("B","R") &
                         olddat$cultivar_n2 %in% 
                         c(1,3,5,7,9), "white", "yellow") #return color based on last values

olddat$last1 <- str_sub(olddat$cultivar_name,-1,-1)
olddat$last2 <-str_sub(olddat$cultivar_name,-2,-1)
olddat$cultivar_br <- str_sub(olddat$cultivar_name,1,3) #make breeder letters
olddat$cultivar_br1 <- readr::parse_number(olddat$cultivar_br)
olddat$breeder <- ifelse(olddat$cultivar_br1 %in% c(NA), "ARC", "SA") #add breeder (private vs public?)
olddat$trait <- "A"
olddat$trait <- if_else(olddat$last1 == "R", "R", olddat$trait) 
olddat$trait <- if_else(olddat$last1 == "B", "B", olddat$trait)
olddat$trait <- if_else(olddat$last2 == "BR", "BR", olddat$trait)
olddat$trait <- if_else(olddat$last2 == "BT", "B", olddat$trait)

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", 
                   "cultivar_name", "alternate", "cultivar_no", "cultivar_br", 
                   "rep", "yield", "color", "trait", "crop", "temp", "irrigated", 
                   "number", "release_year", "land_type")]

olddat <- merge(olddat, location,
                  by.x = "locality", by.y = "locality", 
                  all.x = TRUE, sort = FALSE)

olddat$provence.x <- olddat$provence.y
colnames(olddat)[4] <- "provence"
olddat <- olddat[, !(names(olddat) %in% c("provence.x","provence.y"))]
olddat$technology <- olddat$trait
olddat$technology <- if_else(olddat$technology == "A", "conv", olddat$technology)

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", 
                   "cultivar_name", "alternate", "cultivar_no", "cultivar_br", 
                   "rep", "yield", "color", "technology", "crop", "temp", "irrigated", 
                   "number", "release_year", "land_type")]

summarygm <- olddat %>% group_by(year, technology) %>% summarise(count = n()) ### Check why RR goes back to 1981

oldr <- olddat[olddat$technology == "R",]
oldbr <- olddat[olddat$technology == "BR",]
oldb <- olddat[olddat$technology == "B",]
oldgm <- bind_rows(oldr,oldbr,oldb)
oldgm <- oldgm[!(oldgm$year >= 1998),]

olddat <- olddat[!(olddat$technology %in% c("R","BR","B") & olddat$year <= 1998),] #remove if before 1998 and GE

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", 
                   "cultivar_name", "alternate", "cultivar_no", "cultivar_br", 
                   "rep", "yield", "color", "technology", "crop", "temp", 
                   "irrigated", "number", "release_year", "land_type")]

olddat$Bt <- ifelse(olddat$technology == "B" | olddat$technology == "BR", "Bt", "Conv")

write.csv(olddat,"data/olddatacomplete.csv")
rm(oldr, oldbr, oldb, summarygm, p)

dat <- bind_rows(olddat,dat)
dat$cultivar_name <- trimws(dat$cultivar_name, which= c("both"))
dat$cultivar_name <- toupper(dat$cultivar_name)

summarycult <- dat %>% group_by(year, cultivar_name) %>%
                summarise(count = n())

dat[dat == "AFG4577B"] <- "KKS4577B"
dat[dat == "AFG4522B"] <- "KKS4522B"
dat[dat == "AFG4412B"] <- "KKS4412B"

# fix locality names in merged df
dat$locality <- if_else(dat$locality %in% c("bethelhem", "bethelehem"), "bethlehem", dat$locality) 
dat$locality <- if_else(dat$locality %in% c("bloemkomspruit"), "bloekomspruit", dat$locality)
dat$locality <- if_else(dat$locality %in% c(" coligny"), "coligny", dat$locality)
dat$locality <- if_else(dat$locality %in% c(" wesselsbron"), "wesselsbron", dat$locality)
dat$locality <- if_else(dat$locality %in% c("foiuriesburg"), "fouriesburg", dat$locality)
dat$locality <- if_else(dat$locality %in% c("grooptpan"), "grootpan", dat$locality)
dat$locality <- if_else(dat$locality %in% c("kapsteeel"), "kapsteel", dat$locality)
dat$locality <- if_else(dat$locality %in% c("losdoorn"), "losdoorns", dat$locality)
dat$locality <- if_else(dat$locality %in% c("middleburg"), "middelburg", dat$locality)
dat$locality <- if_else(dat$locality %in% c("losdoorn"), "losdoorns", dat$locality)
dat$locality <- if_else(dat$locality %in% c("wintertonlate", "winterton early"), "winterton", dat$locality)
dat$locality <- if_else(dat$locality %in% c("vilijoenskoon"), "viljoenskroon", dat$locality)
dat$locality <- if_else(dat$locality %in% c("swartruggen"), "swartruggens", dat$locality)
dat$locality <- if_else(dat$locality %in% c("delmas ", "delmas/rayton"), "delmas", dat$locality)
dat$locality <- if_else(dat$locality %in% c("lukehof"), "luckhoff", dat$locality)
dat$locality <- if_else(dat$locality %in% c("mooi river", "mooriver"), "mooirivier", dat$locality)
dat$locality <- if_else(dat$locality %in% c("pocthfestroom", "potchfestroom"), "potchefstroom", dat$locality)
dat$locality <- if_else(dat$locality %in% c("weeselsbron"), "wesselsbron", dat$locality)
dat <- dat[dat$locality!="h"|dat$locality!="ty",]
dat$provence <- trimws(dat$provence, which= c("both"))
dat <- dat[dat$provence!=".",]
dat$provence <- if_else(dat$locality %in% c("windfield"), "FS", dat$provence)
dat$provence <- if_else(dat$locality %in% c("kapsteel"), "NW", dat$provence)
dat$provence <- if_else(dat$locality %in% c("middelburg"), "MP", dat$provence)
dat$provence <- if_else(dat$locality %in% c("greytown"), "KZN", dat$provence)
dat$provence <- as.character(dat$provence)
dat$provence <- as.factor(dat$provence)
dat <- dat[!(dat$provence == "---" | is.na(dat$provence)), ]


# Check if cultivar has more than one observation per year

summarycult <- dat %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult <- summarycult[summarycult$count== "1",]

dat <- merge(dat,summarycult, by = c("year","cultivar_name"),all = TRUE, no.dups= TRUE)
names(dat)[names(dat) == 'count'] <- 'cult_nvals'
dat$cult_nvals <- if_else(dat$cult_nvals %in% c(NA), "0", "1")
dat <- dat[!dat$cult_nvals== "1", ]

# check cultivar if in more than one observation per provence/year
summarycult <- dat %>% group_by(year, provence, cultivar_name) %>%
                summarise(count = n()) 
summarycult <- summarycult[summarycult$count== "1",]
dat <- merge(dat,summarycult, by = c("year","cultivar_name", "provence"),all = TRUE, no.dups= TRUE)
dat$count <- if_else(dat$count %in% c(NA), "0", "1")
dat <- dat[!dat$count== "1", ]

dat <- dat[,c("year", "region", "provence", "locality", "locality_no", 
              "cultivar_name", "alternate", "cultivar_no", "cultivar_br", 
              "rep", "yield", "color", "technology", "Bt", "crop", "temp",
              "irrigated","land_type", "number", "release_year")]


summaryloc <- dat %>% group_by(year, locality) %>% summarise(count = n()) # check location if in more than one year
summaryloc <- summaryloc %>% group_by(locality) %>% summarise (count = n()) # trials per location

dat <- merge(dat,summaryloc,by= "locality")
names(dat)[names(dat) == 'count'] <- 'nval'
dat <- subset(dat, dat$nval!="1") # remove if location only used once


dat$irrigated[is.na(dat$irrigated)] <- 0
dat$land_type[is.na(dat$land_type)] <- ""
dat$land_type[dat$land_type == "Irrigation"] <- "Irrigated"
dat$irrigated <- if_else(dat$land_type == "Irrigated", 1, dat$irrigated)

dat <- dat[,c("year", "provence", "locality","cultivar_name", 
              "rep", "yield", "color", "technology", 
              "crop", "irrigated", "release_year")]

rm(list=setdiff(ls(), "dat"))

dat$bt <- ifelse(dat$technology %in% c("B", "BR"), 1, 0)

summaryold <- dat %>% 
  group_by(color, technology, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
bandconv <- dat[!(dat$technology == "R"),]

summaryall <- dat %>% 
  group_by(color, technology, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))


write.csv(dat,"data/allyearsmerge.csv")


```

### Summary Statistics
```{r datasummary stats, include=false}
#summ stats

bandconv <- dat[dat$technology %in% c("B", "conv"),]
bandconv <- bandconv[!bandconv$provence == "LP",]

#yellow bt summ stat

ybtsummarystat <- bandconv[!bandconv$color == "white",]

btsummarystat2 <- ybtsummarystat %>%
    group_by(technology, provence, cultivar_name) %>%
      count()

btsummarystat3 <- btsummarystat2 %>%
    group_by(technology,provence) %>%
      count()

btsummarystat4 <- ybtsummarystat  %>%
    group_by(technology, provence) %>%
      count()

btsummarystat5 <- ybtsummarystat  %>%
    group_by(technology, provence, locality) %>%
      count()
btlocal <- btsummarystat5  %>%
    group_by(technology, provence) %>%
      count()

ybtsummarystat <- ybtsummarystat %>%
  group_by(technology, provence, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T),
                      SD = sd(yield, na.rm = T),
                      min = min(year, na.rm = T),
                      max = max(year, na.rm = T))

ybtsummarystat <- merge(ybtsummarystat, btsummarystat3, by = c("provence","technology"))
names(ybtsummarystat)[names(ybtsummarystat) == "n"] <- "num_of_cultivars"
names(btsummarystat4)[names(btsummarystat4) == "n"] <- "num_of_observations"
ybtsummarystat <- merge(ybtsummarystat, btsummarystat4, by = c("provence","technology"))
ybtsummarystat <- merge(ybtsummarystat, btlocal, by = c("provence","technology"))
names(ybtsummarystat)[names(ybtsummarystat) == "n"] <- "num_of_localities"


ybtsummarystat <- ybtsummarystat %>%
            gt(rowname_col = "province") %>%
  tab_header(
    title = "Characteristics of Provinces- Yellow",
    subtitle = glue::glue("observations included in sample")
  ) %>%
  cols_label(
    provence = html("Province"),
    mean = html("Average Yield"),
    min = html("Min Year"),
    max = html("Max Year"),
    num_of_cultivars = html("num of cultivars"),
    num_of_observations = html("num of observations"),
    num_of_localities= html("num of localities")) %>%
  cols_align(
    align = "center",
    columns = everything())
  
write.csv(ybtsummarystat,"ybtsummarystat.csv")

#white bt summ stat
wbtsummarystat <- bandconv[!bandconv$color == "yellow",]


btsummarystat2 <- wbtsummarystat %>%
    group_by(technology, provence, cultivar_name) %>%
      count()

btsummarystat3 <- btsummarystat2 %>%
    group_by(technology,provence) %>%
      count()

btsummarystat4 <- wbtsummarystat  %>%
    group_by(technology, provence) %>%
      count()

btsummarystat5 <- wbtsummarystat  %>%
    group_by(technology, provence, locality) %>%
      count()
btlocal <- btsummarystat5  %>%
    group_by(technology, provence) %>%
      count()

wbtsummarystat <- wbtsummarystat %>%
  group_by(technology, provence, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T),
                      SD = sd(yield, na.rm = T),
                      min = min(year, na.rm = T),
                      max = max(year, na.rm = T))

wbtsummarystat <- merge(wbtsummarystat, btsummarystat3, by = c("provence","technology"))
names(wbtsummarystat)[names(wbtsummarystat) == "n"] <- "num_of_cultivars"
names(btsummarystat4)[names(btsummarystat4) == "n"] <- "num_of_observations"
wbtsummarystat <- merge(wbtsummarystat, btsummarystat4, by = c("provence","technology"))
wbtsummarystat <- merge(wbtsummarystat, btlocal, by = c("provence","technology"))
names(wbtsummarystat)[names(wbtsummarystat) == "n"] <- "num_of_localities"


wbtsummarystat <- wbtsummarystat %>%
            gt(rowname_col = "province") %>%
  tab_header(
    title = "Characteristics of Provinces- White",
    subtitle = glue::glue("observations included in sample")
  ) %>%
  cols_label(
    provence = html("Province"),
    mean = html("Average Yield"),
    min = html("Min Year"),
    max = html("Max Year"),
    num_of_cultivars = html("num of cultivars"),
    num_of_observations = html("num of observations"),
    num_of_localities= html("num of localities")) %>%
  cols_align(
    align = "center",
    columns = everything())
  
write.csv(wbtsummarystat,"wbtsummarystat.csv")


# Just B obs (no conv)
bonly <- dat[(dat$technology == "B"),]

bonlysummarystat <- bonly %>%
  group_by(technology, provence, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T),
                      SD = sd(yield, na.rm = T),
                      min = min(year, na.rm = T),
                      max = max(year, na.rm = T))

bonlysummarystat2 <- bonly %>%
    group_by(year, provence) %>%
      count()

breshape <- reshape(bonlysummarystat2, idvar = "year", v.names = "provence", timevar = "provence", direction = "wide")

saveRDS(dat, "data/finalpanel.rds")
dat <- readRDS("data/finalpanel.rds")

```



