---
title: "Maize outline"
author: "Courtney Cooper"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Get Data and Preprocess
```{r data, include=FALSE}
rm(list=ls()) # Caution: this clears the Environment

if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(dplyr, ggplot2, stringr, stringi,readr)
library(ggplot2)


# Read data and stack
rawdat <- list.files(path="data/rawdat", pattern="*csv", full.names = T)
rawdat <- lapply(rawdat, read.csv)
dat <- do.call("rbind", rawdat)
dat$Region <- tolower(dat$Region)
dat$locality <- tolower(dat$locality)
dat$yield <- as.numeric(dat$yield)

write.csv(dat, "data/allnewyears.csv")
rm(rawdat)

```

```{r data combining,include=false}
cultivar <- read.csv("data/metadata/cultivarlist.csv")
cultivar$variety_trim <- toupper(cultivar$variety_trim)
cultivar <- cultivar[, !(names(cultivar) %in% c("variety","technology"))]
names(cultivar)[names(cultivar) == "variety_trim"] <- "cultivar_name"
names(cultivar)[names(cultivar) == "X"] <- "technology"
dat$cultivar_name <- toupper(dat$cultivar_name)
dat$cultivar_name <- trimws(dat$cultivar_name, which= c("both"))


dat <- merge(dat,cultivar,by = "cultivar_name")
names(dat)[names(dat) == "Year"] <- "year"
names(dat)[names(dat) == "Provence"] <- "provence"
names(dat)[names(dat) == "Region"] <- "region"
names(dat)[names(dat) == "Rep"] <- "rep"
names(dat)[names(dat) == "Year"] <- "year"
names(dat)[names(dat) == "breeder.x"] <- "breeder"
dat <- dat[, !(names(dat) %in% c("Yellow","White","variety","breeder.y"))]
dat$alternate <- trimws(dat$alternate, which= c("both"))

write.csv(dat, "data/allnewyearsmerge.csv")
```

### Average and Summaries 

```{r data summaries}

dat$color <- tolower(dat$color)
names(dat)[names(dat) == "Irrigated"] <- "irrigated"
dat$technology <- gsub("0", "conv", dat$technology)

dat <- dat[c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "breeder", "rep", "yield", "color", "technology", "crop", "temp", "irrigated", "number", "release_year")]

summarynew <- dat %>% 
  group_by(color, technology, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(summarynew, aes(year, mean))
p + geom_smooth(aes(color=technology), size = 1)

write.csv(summarynew, "output/summary.csv")
```

```{r data merging, include=false}
olddat <- read.csv("data/metadata/allmaize1980_2010.csv")
location <- read.csv("data/metadata/oldlocality.csv")

location$locality <- tolower(location$locality)
olddat$locality <- tolower(olddat$locality)

olddat <- olddat[!(olddat$yield == "" | is.na(olddat$yield)), ]
olddat <- olddat[olddat$yield >= 0, ]
olddat$cultivar_name <- str_replace_all(string=olddat$cultivar_name, 
                                        pattern=" ", repl="")

olddat$cultivar_n <- str_sub(olddat$cultivar_name,-1) #create columns with last values
olddat$cultivar_n1 <- str_sub(olddat$cultivar_name,-2,-2)
olddat$cultivar_n2 <- str_sub(olddat$cultivar_name,-3,-3)

olddat$color <- ifelse(olddat$cultivar_n %in% c("W",1,3,5,7,9)
                        |olddat$cultivar_n %in% c("B","R") &
                         olddat$cultivar_n1 %in% c(1,3,5,7,9)
                        |olddat$cultivar_n %in% c("B","R") &
                         olddat$cultivar_n1 %in% c("B","R") &
                         olddat$cultivar_n2 %in% 
                         c(1,3,5,7,9), "white", "yellow") #return color based on last values

olddat$last1 <- str_sub(olddat$cultivar_name,-1,-1)
olddat$last2 <-str_sub(olddat$cultivar_name,-2,-1)

olddat$cultivar_br <- str_sub(olddat$cultivar_name,1,3) #make breeder letters
olddat$cultivar_br1 <- tidyr::extract_numeric(olddat$cultivar_br)
olddat$breeder <- ifelse(olddat$cultivar_br1 %in% c(NA), "ARC", "SA") #add breeder (private vs public?)

olddat$trait <- "A"
olddat$trait <- if_else(olddat$last1 == "R", "R", olddat$trait) 
olddat$trait <- if_else(olddat$last1 == "B", "B", olddat$trait)
olddat$trait <- if_else(olddat$last2 == "BR", "BR", olddat$trait)
olddat$trait <- if_else(olddat$last2 == "BT", "B", olddat$trait)

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "cultivar_br", "rep", "yield", "color", "trait", "crop", "temp", "irrigated", "number", "release_year", "land_type")]

olddat <- merge(olddat, location,
                  by.x = "locality", by.y = "locality", 
                  all.x = TRUE, sort = FALSE)

olddat$provence.x <- olddat$provence.y
colnames(olddat)[4] <- "provence"
olddat <- olddat[, !(names(olddat) %in%
                           c("provence.x","provence.y"))]
olddat$technology <- olddat$trait
olddat$technology <- if_else(olddat$technology == "A", 
                               "conv", olddat$technology)

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "cultivar_br", "rep", "yield", "color", "technology", "crop", "temp", "irrigated", "number", "release_year", "land_type")]

summarygm <- olddat %>% group_by(year, technology) %>% summarise(count = n()) ### Check why RR goes back to 1981

oldr <- olddat[olddat$technology == "R",]
oldbr <- olddat[olddat$technology == "BR",]
oldb <- olddat[olddat$technology == "B",]
oldgm <- bind_rows(oldr,oldbr,oldb)
oldgm <- oldgm[!(oldgm$year >= 1998),]

olddat <- olddat[!(olddat$technology %in% 
                     c("R","BR","B") & olddat$year <= 1998),] #remove if before 1998 and GE

olddat <- olddat[c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "cultivar_br", "rep", "yield", "color", "technology", "crop", "temp", "irrigated", "number", "release_year", "land_type")]

olddat$Bt <- ifelse(olddat$technology == "B" | 
                      olddat$technology == "BR", "Bt", "Conv")

write.csv(olddat,"data/olddatacomplete.csv")
write.csv(cultivar, "data/cultivardict.csv")


dat <- bind_rows(olddat,dat)
dat$cultivar_name <- trimws(dat$cultivar_name, which= c("both"))
dat$cultivar_name <- toupper(dat$cultivar_name)

summarycult <- dat %>% group_by(year, cultivar_name) %>%
                summarise(count = n())

dat[dat == "AFG4577B"] <- "KKS4577B"
dat[dat == "AFG4522B"] <- "KKS4522B"
dat[dat == "AFG4412B"] <- "KKS4412B"


dat$locality <- if_else(dat$locality %in% 
                               c("bethelhem", "bethelehem"), 
                             "bethlehem", dat$locality) #fix locality names in merged df
dat$locality <- if_else(dat$locality %in% 
                               c("bloemkomspruit"), 
                             "bloekomspruit", dat$locality)
dat$locality <- if_else(dat$locality %in% 
                               c(" coligny"), 
                             "coligny", dat$locality)
dat$locality <- if_else(dat$locality %in% 
                               c(" wesselsbron"), "wesselsbron", dat$locality)
dat$locality <- if_else(dat$locality %in% 
                               c("foiuriesburg"), "fouriesburg", dat$locality)
dat$locality <- if_else(dat$locality %in% 
                               c("grooptpan"), 
                             "grootpan", dat$locality)
dat$locality <- if_else(dat$locality %in% 
                               c("kapsteeel"), "kapsteel", dat$locality)
dat$locality <- if_else(dat$locality %in% c("losdoorn"), "losdoorns", dat$locality)
dat$locality <- if_else(dat$locality %in% c("middleburg"), "middelburg", dat$locality)
dat$locality <- if_else(dat$locality %in% c("losdoorn"), "losdoorns", dat$locality)
dat$locality <- if_else(dat$locality %in% c("wintertonlate", "winterton early"), "winterton", dat$locality)
dat$locality <- if_else(dat$locality %in% c("vilijoenskoon"), "viljoenskroon", dat$locality)
dat$locality <- if_else(dat$locality %in% c("swartruggen"), "swartruggens", dat$locality)
dat$locality <- if_else(dat$locality %in% c("delmas ", "delmas/rayton"), "delmas", dat$locality)
dat$locality <- if_else(dat$locality %in% c("lukehof"), "luckhoff", dat$locality)
dat$locality <- if_else(dat$locality %in% c("mooi river", "mooriver"), "mooirivier", dat$locality)
dat$locality <- if_else(dat$locality %in% c("pocthfestroom", "potchfestroom"), "potchefstroom", dat$locality)
dat$locality <- if_else(dat$locality %in% c("weeselsbron"), "wesselsbron", dat$locality)
dat <- dat[dat$locality!="h"|dat$locality!="ty",]
dat$provence <- trimws(dat$provence, which= c("both"))
dat <- dat[dat$provence!=".",]
dat$provence <- if_else(dat$locality %in% c("windfield"), "FS", dat$provence)
dat$provence <- if_else(dat$locality %in% c("kapsteel"), "NW", dat$provence)
dat$provence <- if_else(dat$locality %in% c("middelburg"), "MP", dat$provence)
dat$provence <- if_else(dat$locality %in% c("greytown"), "KZN", dat$provence)
dat$provence <- as.character(dat$provence)
dat$provence <- as.factor(dat$provence)
dat <- dat[!(dat$provence == "---" | is.na(dat$provence)), ]

release <- subset(cultivar, select = c(cultivar_name, release_year))
release$cultivar_name <- trimws(release$cultivar_name, which= c("both"))
dat <- merge(dat,release, by="cultivar_name",all = TRUE)
dat <- dat[!(dat$yield == "" | is.na(dat$yield)), ]

names(dat)[names(dat) == "release_year.y"] <- "release_year"

dat <- dat[,c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "cultivar_br", "rep", "yield", "color", "technology", "Bt", "crop", "temp", "irrigated", "number", "release_year", "land_type")]



summarycult <- dat %>% group_by(cultivar_name, year, release_year) %>% summarise(count = n())

norelease <- dat[dat$release_year == "",]

summaryrelease <- norelease %>% group_by(release_year, cultivar_name) %>% 
  summarise(count = n())
write.csv(summaryrelease, "output/noreleasedate.csv")

### Left off here - identify cultivars with no release date

####

dat$cultivar_release <- str_sub(dat$release_year,1,4)

summarycult <- dat %>% group_by(year, cultivar_name) %>%
                summarise(count = n()) # check cultivar if in more than one year

summarycult2 <- summarycult %>% group_by(cultivar_name) %>% 
                summarise (count = n())

dat <- merge(dat,summarycult2, by="cultivar_name")
names(dat)[names(dat) == 'count'] <- 'cult_nvals'
dat <- dat[!dat$cult_nvals== "1",]


summarycult <- dat %>% group_by(year, provence, cultivar_name) %>%
                summarise(count = n()) # check cultivar if in more than one obersvation per provence/year
##add unique value catch
dat <- merge(dat,summarycult, by="cultivar_name")

names(dat)[names(dat) == 'count'] <- 'cult_nvals2'
dat <- dat[!dat$cult_nvals2== "1",]



##################
summaryloc <- dat %>% group_by(year, locality) %>% 
  summarise(count = n()) # check location if in more than one year
summaryloc <- summaryloc %>% group_by(locality) %>% 
  summarise (count = n()) # trials per location

dat <- merge(dat,summaryloc,by= "locality")
names(dat)[names(dat) == 'count'] <- 'nval'
dat <- subset(dat, dat$nval!="1") # remove if location only used once


dat$irrigated[is.na(dat$irrigated)] <- 0
dat$land_type[is.na(dat$land_type)] <- ""
dat$land_type[dat$land_type == "Irrigation"] <- "Irrigated"
dat$irrigated <- if_else(dat$land_type == "Irrigated", 1, dat$irrigated)

dat <- dat[,c("year", "region", "provence", "locality", "locality_no", "cultivar_name", "alternate", "cultivar_no", "cultivar_br", "rep", "yield", "color", "technology", "Bt", "crop", "temp", "irrigated", "number", "release_year")]


rm(list=setdiff(ls(), "dat"))

dat$bt <- ifelse(dat$technology %in% c("B", "BR"), 1, 0)

summaryold <- dat %>% 
  group_by(color, technology, Bt, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))
noR <- dat[!(dat$technology == "R"),]

summaryall <- dat %>% 
  group_by(color, technology, year, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(dat, aes(year, mean))
## p + geom_smooth(aes(color=dat$Bt), size = 1, method="lm")

write.csv(dat,"data/allyearsmerge.csv")

```

```{r datasummary stats, include=false}
#summ stats

genetics <- dat[dat$cultivar_name == "CRN3505",]
genetics2 <- dat[dat$cultivar_name == "DKC78-15B",]
genetics <- bind_rows(genetics,genetics2)
genetics <- genetics[,c("year", "provence", "locality", "cultivar_name", "yield", "color", "technology", "Bt")]

summarygen <- genetics %>% 
  group_by(year, cultivar_name, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(data = summarygen, aes(x = year, y = mean)) + geom_smooth(aes(color=cultivar_name))

print(p)

write.csv(genetics, "output/cultivartest.csv")

summary(dat$provence)

#number of trials by year

summaryloc <- dat %>% group_by(year, provence, GM) %>% summarise(count = n()) # check location if in more than one year
summaryloc2 <- summaryloc %>% group_by() %>% summarise(count = n())
summaryloc3 <- summaryloc %>% group_by(year) %>% summarise (count = n()) # show how many trials per year

write.csv(summaryloc, "trialsbyyear.csv")

# white mean by year
color <- dat %>% group_by(color) %>% summarise (count = n())
pwhite <- noR %>% filter(color == "white") %>%
            group_by(color,technology, year, .add = FALSE) %>%
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p<- ggplot(pwhite, aes(year, mean)) + geom_smooth(aes(color=technology), size = 1) + ggtitle('White Yield Over Time')
plot(p)


pdry <- dat %>% filter(irrigated == 0) %>%
           group_by(color,technology, year, .add = FALSE) %>%
           summarise(mean = mean(yield, na.rm = T), 
           SD = sd(yield, na.rm = T))

# Bt mean by year
pbt <- dat %>% filter(technology == "B") %>%
            group_by(color, year, .add = FALSE) %>%
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(pbt, aes(year, mean)) + geom_smooth(aes(color=color), size = 1) + ggtitle('Bt Yield Over Time')
plot(p)




# RR mean by year
prr <- dat %>% filter(technology == "R") %>%
            group_by(color, year, .add = FALSE) %>%
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(prr, aes(year, mean))
p + geom_smooth(aes(color=color), size = 1)

# number of cultivars by year
summarydry <- dat %>% group_by(irrigated) %>% summarise(count = n())
summarycult <- dat %>% group_by(cultivar_name) %>% summarise(count = n())
summarycult <- dat %>% group_by(year, cultivar_name) %>% summarise(count = n()) 
summarycult <- summarycult %>% group_by(year) %>% summarise (count = n())


# number of trials by cultivar
summaryloccult <- dat %>% group_by(cultivar_name,year, locality) %>% summarise(count = n()) 
summaryloccult <- summaryloccult %>% group_by(cultivar_name) %>% summarise (count = n())

write_rds(dat, "data/finalpanel.rds")
dat <- readRDS("data/finalpanel.rds")

```


###cultivar tests
```{}

genetics <- dat[dat$cultivar_name == "CRN3505",]

genetics3 <- dat[dat$cultivar_name == "DKC78-15B",]

genetics2 <- dat[dat$cultivar_name == "DKC78-45BR",]

genetics <- bind_rows(genetics,genetics2, genetics3)

genetics <- genetics[,c("year", "provence", "locality", "cultivar_name", "yield", "color", "technology", "Bt")]

summarygen <- genetics %>% 
  group_by(year, cultivar_name, Bt, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(data = summarygen, aes(x = year, y = mean)) + geom_smooth(aes(color=cultivar_name))
print(p)


genetics <- dat[dat$cultivar_name == "PAN4A-172",]

genetics2 <- dat[dat$cultivar_name == "PAN4B-472B",]

genetics3 <- dat[dat$cultivar_name == "PAN4R-872BR",]

genetics4 <- dat[dat$cultivar_name == "PAN4R-672R",]

genetics <- bind_rows(genetics,genetics2)

genetics <- genetics[,c("year", "provence", "locality", "cultivar_name", "yield", "color", "technology", "Bt")]

summarygen <- genetics %>% 
  group_by(year, cultivar_name, .add = FALSE) %>% 
            summarise(mean = mean(yield, na.rm = T), 
            SD = sd(yield, na.rm = T))

p <- ggplot(data = summarygen, aes(x = year, y = mean)) + geom_smooth(aes(color=cultivar_name))
print(p)













CRN3505 <- dat[dat$cultivar_name == "CRN3505",]

CRN7821BT <- dat[dat$cultivar_name == "CRN7821BT",]
US9612 <- dat[dat$cultivar_name == "US9612",]
A152 <- dat[dat$cultivar_name == "A152",]



summarycult <- dat %>% group_by(cultivar_name, year, release_year) %>% summarise(count = n())

dat$release_year[is.na(dat$release_year)] <- ""

norelease <- dat[dat$release_year == "",]

summaryrelease <- norelease %>% group_by(release_year, cultivar_name) %>% 
  summarise(count = n())










```

### BT maize reduces yield risk

### BT yield gains vary across dimensions

### BT white maize has larger yield gains than GM yellow maize



